### ISSUE TITLE
Direct all the traffic from public cloud to private cloud

### ISSUE THREAD

**Issue by rahulbahal7** [BU-NU-CLOUD-SP16/cloud-gateway#3]
## Issue

Route all the traffic from public cloud to the private cloud if it belongs to a subnet in the public cloud that contains resources(machine's) connected to the private cloud through the VCG's.

I have two solutions for this so far:
### Solution 1

Set the out-bound traffic rules in the public cloud route table to send the traffic to the private cloud based on the origin of the traffic.
### Solution 2

Route all the traffic to our VCG on the public cloud side. Since there is already a tunnel, all traffic will be sent to the private cloud.
`Instead of 0.0.0.0/0 (which implies Internet Gateway) we will add the default route as the address of our VCG in the VPC's route table`

For now, solution 2 seems like a cleaner solution. I will be updating this issue with more details as I run into more information.

**Comment by singhay** [comment]
Solution 2 is elegant

**Comment by ChienliMa** [comment]
Setting right subnet to `0.0.0.0/0` will cause another problem: overlapping left and right subnet.

Also, as I and @rahulbahal7  have seen, doing so will make this machine inaccessible.
We have no idea why this happened, because theoretically this machine should be accessible on the other side on tunnel.
A good way to figure this out is to setup a tunnel between machines in VirtualBox and reproduce this situation. Since we have direct access to this machine we can still trouble shooting after the network is crashed.

Also, from the mailing list of StrongSwan it seems that StrongSwan support such king of configuration. 

But I am looking for a better solution.

**Comment by ChienliMa** [comment]
Following code is my new configuration that allow one cloud to connect to the Internet through the other gateway, i.e. route all traffic to the other gateway

```
config setup

conn %default
     ikelifetime=60m
     keylife=20m
     rekeymargin=3m
     keyingtries=1
     authby=secret
     keyexchange=ikev2
     mobike=no

conn viginia-oregon 
     leftid = y.y.y.y
     left = 10.0.0.27 
     leftsubnet=10.0.0.0/16
     rightid=x.x.x.x
     right=x.x.x.x
     rightsubnet=10.1.0.0/16
     auto=add

conn passthrough
     type=passthrough
     leftsubnet=10.0.0.0/16, x.x.x.x, y.y.y.y
     authby=never
     auto=route
```

This is quite straight froward, this gateway set rightsubnet as 0.0.0.0/0 to route all traffic to the remote gateway, since he want to access internet. However, some traffic should not be routed to tunnel. This is why we add a new `passthrough` connection, which will keep traffic tothe leftsubnet away from tunnel. Note that this connection is very important is we set rightsubnet to 0.0.0.0/0. Without this we will loss connection to this gateway.

At last, to we need a NAT at the gateway that faces the Internet to replace the src address with a public facing IP address(which is actually done by IGW provided by amazon):

```
sudo iptables -t nat -A POSTROUTING -s <left_ip_address> -o <interface> -j MASQURADE
```

BTW, I recommend to switch to StrongSwan for it has better documentation and is still under maintained.
